[build]
  # Asegúrate de que Netlify sepa DÓNDE buscar las funciones.
  functions = "netlify/functions"

[functions]
  # Esto es lo que te dije antes, para incluir tus CSV.
  included_files = ["netlify/functions/data/**"]